---
version: '3.5'
services:

  broker1:
    image: confluentinc/cp-kafka:7.4.0
    hostname: broker1
    container_name: broker1
    ports:
      - "9092:9092"
      - "9095:9093"
    environment:
      KAFKA_broker_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker1:29092,PLAINTEXT_HOST://localhost:9092,EXTERNAL://localhost:9093'
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/jaas/kafka_oauth.conf"
      KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/kafka/jaas/log4j.properties"
      KAFKA_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker1:29093,2@broker2:29093,3@broker3:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker1:29092,CONTROLLER://broker1:29093,PLAINTEXT_HOST://0.0.0.0:9092,EXTERNAL://localhost:9093'
      KAFKA_SASL_ENABLED_MECHANISMS: 'PLAIN,OAUTHBEARER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_SECURITY_PROTOCOL: 'SASL_PLAINTEXT'
      KAFKA_SUPER_USERS: 'User:admin;User:mds;User:superUser;User:ANONYMOUS'
      KAFKA_AUTHORIZER_CLASS_NAME: 'org.apache.kafka.metadata.authorizer.StandardAuthorizer'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'zlFiTJelTOuhnklFwLWixw'
      KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: 'OAUTHBEARER'
      KAFKA_SASL_OAUTHBEARER_TOKEN_ENDPOINT_URL: 'http://keycloak:8080/realms/kafka/protocol/openid-connect/token'
      KAFKA_SASL_OAUTHBEARER_JWKS_ENDPOINT_URL: 'http://keycloak:8080/realms/kafka/protocol/openid-connect/certs'
      KAFKA_LISTENER_NAME_EXTERNAL_OAUTHBEARER_SASL_LOGIN_CALLBACK_HANDLER_CLASS: 'org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerLoginCallbackHandler'
#      KAFKA_SASL_LOGIN_CALLBACK_HANDLER_CLASS: 'io.confluent.kafka.server.plugins.auth.token.TokenBearerServerLoginCallbackHandler'
      KAFKA_LISTENER_NAME_EXTERNAL_OAUTHBEARER_SASL_SERVER_CALLBACK_HANDLER_CLASS: 'org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerValidatorCallbackHandler'
#     KAFKA_LISTENER_NAME_EXTERNAL_OAUTHBEARER_SASL_SERVER_CALLBACK_HANDLER_CLASS: 'io.confluent.kafka.server.plugins.auth.token.TokenBearerValidatorCallbackHandler'
    volumes:
      - ./jaas:/etc/kafka/jaas
#      - ./data/kafka1:/tmp/kraft-combined-logs
#      - ./data/log/log1:/var/log

  broker2:
    image: confluentinc/cp-kafka:7.4.0
    hostname: broker2
    container_name: broker2
    ports:
      - "9093:9092"
      - "9096:9093"
    environment:
      KAFKA_broker_ID: 2
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker2:29092,PLAINTEXT_HOST://localhost:9092,EXTERNAL://localhost:9093'
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/jaas/kafka_oauth.conf"
      KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/kafka/jaas/log4j.properties"
      KAFKA_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 2
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker1:29093,2@broker2:29093,3@broker3:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker2:29092,CONTROLLER://broker2:29093,PLAINTEXT_HOST://0.0.0.0:9092,EXTERNAL://localhost:9093'
      KAFKA_SASL_ENABLED_MECHANISMS: 'PLAIN,OAUTHBEARER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_SECURITY_PROTOCOL: 'SASL_PLAINTEXT'
      KAFKA_SUPER_USERS: 'User:admin;User:mds;User:superUser;User:ANONYMOUS'
      KAFKA_AUTHORIZER_CLASS_NAME: 'org.apache.kafka.metadata.authorizer.StandardAuthorizer'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'zlFiTJelTOuhnklFwLWixw'
      KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: 'OAUTHBEARER'
      KAFKA_SASL_OAUTHBEARER_TOKEN_ENDPOINT_URL: 'http://keycloak:8080/realms/kafka/protocol/openid-connect/token'
      KAFKA_SASL_OAUTHBEARER_JWKS_ENDPOINT_URL: 'http://keycloak:8080/realms/kafka/protocol/openid-connect/certs'
      KAFKA_LISTENER_NAME_EXTERNAL_OAUTHBEARER_SASL_LOGIN_CALLBACK_HANDLER_CLASS: 'org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerLoginCallbackHandler'
#      KAFKA_LISTENER_NAME_EXTERNAL_OAUTHBEARER_SASL_LOGIN_CALLBACK_HANDLER_CLASS: 'io.confluent.kafka.server.plugins.auth.token.TokenBearerServerLoginCallbackHandler'
      KAFKA_LISTENER_NAME_EXTERNAL_OAUTHBEARER_SASL_SERVER_CALLBACK_HANDLER_CLASS: 'org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerValidatorCallbackHandler'
#     KAFKA_LISTENER_NAME_EXTERNAL_OAUTHBEARER_SASL_SERVER_CALLBACK_HANDLER_CLASS: 'io.confluent.kafka.server.plugins.auth.token.TokenBearerValidatorCallbackHandler'
    volumes:
      - ./jaas:/etc/kafka/jaas
#      - ./data/kafka2:/tmp/kraft-combined-logs
#      - ./data/log/log2:/var/log

  broker3:
    image: confluentinc/cp-kafka:7.4.0
    hostname: broker3
    container_name: broker3
    ports:
      - "9094:9092"
      - "9097:9093"
    environment:
      KAFKA_broker_ID: 3
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker3:29092,PLAINTEXT_HOST://localhost:9092,EXTERNAL://localhost:9093'
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/jaas/kafka_oauth.conf"
      KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/kafka/jaas/log4j.properties"
      KAFKA_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 3
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker1:29093,2@broker2:29093,3@broker3:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker3:29092,CONTROLLER://broker3:29093,PLAINTEXT_HOST://0.0.0.0:9092,EXTERNAL://localhost:9093'
      KAFKA_SASL_ENABLED_MECHANISMS: 'PLAIN,OAUTHBEARER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_SECURITY_PROTOCOL: 'SASL_PLAINTEXT'
      KAFKA_SUPER_USERS: 'User:admin;User:mds;User:superUser;User:ANONYMOUS'
      KAFKA_AUTHORIZER_CLASS_NAME: 'org.apache.kafka.metadata.authorizer.StandardAuthorizer'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'zlFiTJelTOuhnklFwLWixw'
      KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: 'OAUTHBEARER'
      KAFKA_SASL_OAUTHBEARER_TOKEN_ENDPOINT_URL: 'http://keycloak:8080/realms/kafka/protocol/openid-connect/token'
      KAFKA_SASL_OAUTHBEARER_JWKS_ENDPOINT_URL: 'http://keycloak:8080/realms/kafka/protocol/openid-connect/certs'
      KAFKA_LISTENER_NAME_EXTERNAL_OAUTHBEARER_SASL_LOGIN_CALLBACK_HANDLER_CLASS: 'org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerLoginCallbackHandler'
#      KAFKA_LISTENER_NAME_EXTERNAL_OAUTHBEARER_SASL_LOGIN_CALLBACK_HANDLER_CLASS: 'io.confluent.kafka.server.plugins.auth.token.TokenBearerServerLoginCallbackHandler'
      KAFKA_LISTENER_NAME_EXTERNAL_OAUTHBEARER_SASL_SERVER_CALLBACK_HANDLER_CLASS: 'org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerValidatorCallbackHandler'
#     KAFKA_LISTENER_NAME_EXTERNAL_OAUTHBEARER_SASL_SERVER_CALLBACK_HANDLER_CLASS: 'io.confluent.kafka.server.plugins.auth.token.TokenBearerValidatorCallbackHandler'
    volumes:
      - ./jaas:/etc/kafka/jaas
#      - ./data/kafka3:/tmp/kraft-combined-logs
#      - ./data/log/log3:/var/log


  kafka-ui:
    container_name: kafka-ui3
    image: docker.redpanda.com/vectorized/console:latest
    ports:
      - "8081:8080"
    volumes:
      - ./kowl/config.yaml:/tmp/kowl/config.yaml
    depends_on:
      - broker1
      - broker2
      - broker3
    environment:
      KAFKA_BROKERS: 'broker1:29092,broker2:29092,broker3:29092'
  #   entrypoint: ./console --config.filepath=/tmp/kowl/config.yaml

  kafka-exporter:
      container_name: kafka-exporter
      image: docker.io/bitnami/kafka-exporter:latest
      ports:
        - "9308:9308"
      environment:
        KAFKA_SERVER: 'PLAINTEXT://broker1:29092,PLAINTEXT://broker2:29092,PLAINTEXT://broker3:29092'
        KAFKA_AUTHENTICATION_PROTOCOL: 'PLAINTEXT'
      command: --kafka.server=broker1:29092 --kafka.server=broker2:29092 --kafka.server=broker3:29092
#
#  kafka_exporter2:
#    container_name: kafka-exporter2
#    image: danielqsj/kafka-exporter:latest
#    ports:
#      - "9308:9308"
#    command: --kafka.server=broker1:29092

#  control-center:
#    image: confluentinc/cp-enterprise-control-center:7.4.0
#    hostname: control-center
#    container_name: control-center
#    depends_on:
#      - broker1
#      - broker2
#      - broker3
#    ports:
#      - "9021:9021"
#    environment:
#      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker1:29092,broker2:29092,broker3:29092'
#      CONTROL_CENTER_REPLICATION_FACTOR: 1
#      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
#      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
#      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
#      PORT: 9021

#  keycloak2:
#    container_name: keycloak2
#    image: jboss/keycloak:latest
#    ports:
#      - 8081:8080
#    environment:
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: admin
#      KEYCLOAK_LOGLEVEL: DEBUG

#    command: start-dev
#networks:
#  test:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 172.16.238.0/24
#          gateway: 172.16.238.1

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --log-level=DEBUG


#  akhq:
#    # build:
#    #   context: .
#    image: tchiotludo/akhq
#    restart: unless-stopped
#    environment:
#      AKHQ_CONFIGURATION: |
#        akhq:
#          connections:
#            docker-kafka-server:
#              properties:
#                bootstrap.servers: "broker1:29092,broker2:29092,broker3:29092"
#    ports:
#      - "8080:8080"

#
#  kafka-ui2:
#    container_name: kafka-ui2
#    image: provectuslabs/kafka-ui:latest
#    ports:
#      - 8085:8085
#    depends_on:
#      - ksqldb-server
#      - broker
#      - schema-registry
#      - connect
#    environment:
#      KAFKA_CLUSTERS_0_NAME: local
#      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092
#      KAFKA_CLUSTERS_0_METRICS_PORT: 9101
#      DYNAMIC_CONFIG_ENABLED: 'true'